[package]
name = "sh_core_service"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.18.0"
tide = "0.16.0"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
ts-rs = "6.2"